contains:
  0:
    - "&8更多信息&7(&8*page-max*&7/&8*page-now*&7)"
    - "*tier-color**@mi-attack-damage*:*!mi-attack-damage* *~mi-attack-damage*"
    - "&7*#mi-attack-damage* *~mi-attack-damage*"
    - "*tier-color**@mi-attack-speed*:*!mi-attack-speed* *~mi-attack-speed*"
    - "&7*#mi-attack-speed* *~mi-attack-speed*"