name: OriginItem
version: '${project.version}'
main: cn.originmc.plugins.originitem.OriginItem
api-version: 1.13
authors: [ Yeqi ]
depend:
  - OriginCore
commands:
  OriginItem:
    aliases:
      - oi
      - oitem